name: rpx
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_13
  - libgcc-ng=15.2.0=h69a702a_13
  - libgomp=15.2.0=he0feb66_13
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h934c35e_13
  - libstdcxx-ng=15.2.0=hdf11a46_13
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.12=hd12c33a_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.2.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.3
      - black==25.1.0
      - blinker==1.9.0
      - braceexpand==0.1.7
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chumpy==0.71
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7
      - contourpy==1.3.2
      - cryptease==0.2.0
      - cryptography==44.0.2
      - cycler==0.12.1
      - cython==3.2.1
      - dash==3.0.0
      - dashscope==1.25.2
      - decorator==5.2.1
      - detectron2==0.6
      - distro==1.9.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.60.1
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hamer==0.0.0
      - httpcore==1.0.9
      - httplib2==0.31.2
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.10
      - imageio==2.37.2
      - importlib-metadata==8.6.1
      - iopath==0.1.9
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jax==0.5.3
      - jaxlib==0.5.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.14.2
      - lxml==5.3.1
      - mano==0.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - mediapy==1.2.4
      - ml-dtypes==0.5.1
      - mmcv==1.3.9
      - mmengine==0.10.7
      - mmpose==0.24.0
      - mpmath==1.3.0
      - multidict==6.2.0
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - narwhals==1.32.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - open3d==0.19.0
      - openai==2.8.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.7
      - plotly==6.0.1
      - portalocker==3.1.1
      - prompt-toolkit==3.0.52
      - propcache==0.3.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pybullet==3.2.7
      - pycocotools==2.0.10
      - pycparser==2.22
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyglet==2.1.11
      - pygments==2.19.1
      - pyopengl==3.1.0
      - pyopengl-accelerate==3.1.9
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pyrootutils==1.0.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.5.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.23.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - smplx==0.1.28
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - stringcase==1.2.0
      - submitit==1.5.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - timm==1.0.15
      - tomli==2.2.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchgeometry==0.1.2
      - torchmetrics==1.7.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.10.0
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.3.0
      - wcwidth==0.2.14
      - webdataset==0.2.111
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/abc/miniconda3/envs/rpx
